import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Vambiental | App",
  description: "Generated by vambiental app",
};
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    
    <html lang="en">
      <body className="overflow-x-hidden bg-light">
      {children}
      </body>
    </html>
  );
}
